var prices = [
  {
    "product": "caramel-dreams",
    "name": "Caramel Dreams",
    "full": true,
    "shot": true,
    "fullPrice": 100,
    "shotPrice": 10,
    "fullSize": [1,2,3],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "four-elements",
    "name": "Four Elements",
    "full": true,
    "shot": true,
    "fullPrice": 200,
    "shotPrice": 20,
    "fullSize": [1,2,3],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "sweet-lemon",
    "name": "Sweet Lemon",
    "full": true,
    "shot": true,
    "fullPrice": 300,
    "shotPrice": 30,
    "fullSize": [1,2,3],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "choco-lovers",
    "name": "Choco Lovers",
    "full": true,
    "shot": true,
    "fullPrice": 400,
    "shotPrice": 40,
    "fullSize": [1,2,3],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "soft-hazelnuts",
    "name": "Soft Hazelnuts",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1,2,3],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "three-elements",
    "name": "Three Elements",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1,2,3],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "crazy-brownie",
    "name": "Crazy Brownie",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [0.5,1,1.5,2],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "dark-explotion",
    "name": "Dark Explotion",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [0.5,1,1.5,2],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "cheesecake-blanco",
    "name": "Cheesecake de Chocolate Blanco con Topping de Fresa/Mora",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1.5,2,2.5],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "cheesecake-oreo",
    "name": "Cheesecake de Oreo con Topping de Chocolate y Oreo",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1.5,2,2.5],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "tiramisu",
    "name": "Tiramisú",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1.5,2,2.5],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "mousse",
    "name": "Mousse de Choco Parchita",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1,2,3],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "milky-rice",
    "name": "Milky Rice",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1.5,2,2.5],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "profiteroles",
    "name": "Profiteroles",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1.5,2,2.5],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "red-velvet",
    "name": "Red Velvet",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1.5,2,2.5],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "passion-nuts",
    "name": "Passion Nuts",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1.5,2,2.5],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "coffee-cake",
    "name": "Coffee Cake",
    "full": true,
    "shot": true,
    "fullPrice": 500,
    "shotPrice": 50,
    "fullSize": [1,2,3],
    "shotSize": [5,8],
    "fullQuantities": [1,2,3,4],
    "shotQuantities": [12,18,24,30,36]
  },
  {
    "product": "alfajores",
    "name": "Alfajores",
    "full": false,
    "shot": false,
    "price": 10,
    "quantities": [24,30,36,42]
  },
  {
    "product": "bomboneria",
    "name": "Bombonería Surtida",
    "full": false,
    "shot": false,
    "price": 10,
    "quantities": [48,60,72,84]
  },
  {
    "product": "tartaletas",
    "name": "Tartaleta de Frutas",
    "full": false,
    "shot": false,
    "price": 10,
    "quantities": [12,24,36,48,60,72,84]
  },
  {
    "product": "chococookies",
    "name": "Chococookies",
    "full": false,
    "shot": false,
    "price": 10,
    "quantities": [12,24,36,48,60,72,84]
  },
  {
    "product": "polvorosas",
    "name": "Polvorosas",
    "full": false,
    "shot": false,
    "price": 10,
    "quantities": [12,24,36,48,60,72,84]
  },
  {
    "product": "macarrones",
    "name": "Macarrones",
    "full": false,
    "shot": false,
    "price": 10,
    "quantities": [12,24,36,48,60,72,84]
  },
  {
    "product": "snowflake",
    "name": "Snowflake",
    "full": false,
    "shot": false,
    "price": 10,
    "quantities": [12,24,36,48,60,72,84]
  }
];
